#:import Factory kivy.factory.Factory
<HelpPopup@Popup>:
    auto_dismiss: True
    pos_hint: {"x": 0, "top": 0.9}
    size_hint: 0.5,0.5
    title: "Home page"
    Label:
        text_size: self.width, None
        text: "The home page allows you to navigate to any screen in the program. "


<ClearDataPopup@Popup>:
    auto_dismiss: True
    pos_hint: {"x": 0, "top": 0.9}
    size_hint: 0.5,0.5
    title: "Clear data"
    Label:
        text_size: self.width, None
        text: "Data cleared. "


# Tells manager which screen it can swap between
WindowManager:
    HomeScreen:
    PlaceOrderScreen:
    FinancialStatementScreen:
    PortfolioScreen:
    OrderBook:





<HomeScreen>
    name: "home"
    # sets background colour
    canvas.before:
        Color:
            rgba: (0.12, 0.65, 0.25, 1)
        Rectangle:
            pos: self.pos
            size: self.size
    FloatLayout:
        size: root.width, root.height

        Button:
            text: "HELP"
            size_hint: (0.3,0.1)
            pos_hint: {"x": 0.01, "y": 0.8}
            background_color: (0.6, 0.85, 0.92, 1)
            on_release: Factory.HelpPopup().open()
        Button:
            text: "Place order"
            size_hint: (0.3,0.1)
            pos_hint: {"x": 0.01, "y": 0.5}
            background_color: (0.6, 0.85, 0.92, 1)
            # switches screen when pressed
            on_release: app.root.current = "PlaceOrder"
        Button:
            text: "View Financial Statements"
            size_hint: (0.3,0.1)
            pos_hint: {"x": 0.01, "y": 0.35}
            background_color: (0.6, 0.85, 0.92, 1)
            on_release: app.root.current = "FinanceStatement"
        Button:
            text: "View Portfolio"
            size_hint: (0.3,0.1)
            pos_hint: {"x": 0.01, "y": 0.2}
            background_color: (0.6, 0.85, 0.92, 1)
            on_release: app.root.current = "portfolio"
        Button:
            text: "Time Skip"
            size_hint: (0.3,0.1)
            pos_hint: {"x": 0.01, "y": 0.05}
            background_color: (0.6, 0.85, 0.92, 1)
        Button:
            text: "View Order Book"
            size_hint: (0.3,0.1)
            pos_hint: {"x": 0.69, "y": 0.5}
            background_color: (0.6, 0.85, 0.92, 1)
            on_release: app.root.current = "OrderBook"
        Button:
            text: "View other portfolios"
            size_hint: (0.3,0.1)
            pos_hint: {"x": 0.69, "y": 0.35}
            background_color: (0.6, 0.85, 0.92, 1)
        Button:
            text: "Clear data"
            size_hint: (0.3,0.1)
            pos_hint: {"x": 0.69, "y": 0.2}
            background_color: (0.6, 0.85, 0.92, 1)
            on_release:
                Factory.ClearDataPopup().open();root.deletion()

<FinancialStatementScreen>
    name: "FinanceStatement"
    # sets background colour
    canvas.before:
        Color:
            rgba: (0.12, 0.65, 0.25, 1)
        Rectangle:
            pos: self.pos
            size: self.size
    FloatLayout:
        Button:
            text: "HELP"
            size_hint: (0.3,0.1)
            pos_hint: {"x": 0.01, "y": 0.85}
            background_color: (0.6, 0.85, 0.92, 1)
        Button:
            text: "BACK"
            size_hint: (0.3,0.1)
            pos_hint: {"x": 0.69, "y": 0.85}
            background_color: (0.6, 0.85, 0.92, 1)
            # switches screen when pressed
            on_release: app.root.current = "home"
        BoxLayout:
            orientation: "vertical"
            size_hint: (1,0.85)
            pos_hint : {"x":0,"y":0}

            Label:
                text: "Financial Values"
                height: "40dp"
                color: (0,0,0,1)

            ScrollView:

                GridLayout:
                    id:table
                    cols: 9
                    height: self.minimum_height




<PlaceOrderScreen>
    name: "PlaceOrder"
    canvas.before:
        Color:
            rgba: (0.12, 0.65, 0.25, 1)
        Rectangle:
            pos: self.pos
            size: self.size
    FloatLayout:
        size: root.width, root.height

        Button:
            text: "HELP"
            size_hint: (0.3,0.1)
            pos_hint: {"x": 0.01, "y": 0.85}
            background_color: (0.6, 0.85, 0.92, 1)
        Button:
            text: "BACK"
            size_hint: (0.3,0.1)
            pos_hint: {"x": 0.69, "y": 0.85}
            background_color: (0.6, 0.85, 0.92, 1)
            # switches screen when pressed
            on_release: app.root.current = "home"
        Label:
            text: "Buy"
            size_hint: (None, None)
            size: ("100dp", "40dp")
            pos_hint: {"x": 0.1, "y": 0.7}
            color: (0, 0, 0, 1)

        Label:
            text: "Enter the company ticker:"
            size_hint: (None, None)
            size: ("100dp", "40dp")
            pos_hint: {"x": 0.1, "y": 0.65}
            color: (0, 0, 0, 1)

        TextInput:
            id:buy_company_input
            text: "0"
            size_hint_x: 0.33
            size_hint_y: None
            height: "40dp"
            pos_hint: {"x": 0, "y": 0.6}
            halign: "right"
            font_size: 20

        Label:
            text: "Enter how many shares you want to buy:"
            size_hint: (None, None)
            size: ("100dp", "40dp")
            pos_hint: {"x": 0.1, "y": 0.55}
            color: (0, 0, 0, 1)

        TextInput:
            id:buy_num_of_shares_input
            text: "0"
            size_hint_x: 0.33
            size_hint_y: None
            height: "40dp"
            pos_hint: {"x": 0, "y": 0.5}
            halign: "right"
            font_size: 20

        Label:
            text: "Enter the share price you want to trade at:"
            size_hint: (None, None)
            size: ("100dp", "40dp")
            pos_hint: {"x": 0.1, "y": 0.45}
            color: (0, 0, 0, 1)

        TextInput:
            id:buy_share_price_input
            text: "0"
            size_hint_x: 0.33
            size_hint_y: None
            height: "40dp"
            pos_hint: {"x": 0, "y": 0.4}
            halign: "right"
            font_size: 20

        Button:
            text: "Place order"
            size_hint: (0.3,0.1)
            pos_hint: {"x": 0.01, "y": 0.2}
            background_color: (0.6, 0.85, 0.92, 1)
            on_release: root.buy()

        Label:
            text: "Sell"
            size_hint: (None, None)
            size: ("100dp", "40dp")
            pos_hint: {"x": 0.6, "y": 0.7}
            color: (0, 0, 0, 1)

        Label:
            text: "Enter the company ticker:"
            size_hint: (None, None)
            size: ("100dp", "40dp")
            pos_hint: {"x": 0.6, "y": 0.65}
            color: (0, 0, 0, 1)

        TextInput:
            id:sell_company_input
            text: "0"
            size_hint_x: 0.33
            size_hint_y: None
            height: "40dp"
            pos_hint: {"x": 0.6, "y": 0.6}
            halign: "right"
            font_size: 20

        Label:
            text: "Enter how many shares you want to sell:"
            size_hint: (None, None)
            size: ("100dp", "40dp")
            pos_hint: {"x": 0.6, "y": 0.55}
            color: (0, 0, 0, 1)

        TextInput:
            id:sell_num_of_shares_input
            text: "0"
            size_hint_x: 0.33
            size_hint_y: None
            height: "40dp"
            pos_hint: {"x": 0.6, "y": 0.5}
            halign: "right"
            font_size: 20

        Label:
            text: "Enter the share price you want to trade at:"
            size_hint: (None, None)
            size: ("100dp", "40dp")
            pos_hint: {"x": 0.6, "y": 0.45}
            color: (0, 0, 0, 1)

        TextInput:
            id:sell_share_price_input
            text: "0"
            size_hint_x: 0.33
            size_hint_y: None
            height: "40dp"
            pos_hint: {"x": 0.6, "y": 0.4}
            halign: "right"
            font_size: 20

        Button:
            text: "Place order"
            size_hint: (0.3,0.1)
            pos_hint: {"x": 0.69, "y": 0.2}
            background_color: (0.6, 0.85, 0.92, 1)
            on_release: root.sell()


<PortfolioScreen>
    name: "portfolio"
    # sets background colour
    canvas.before:
        Color:
            rgba: (0.12, 0.65, 0.25, 1)
        Rectangle:
            pos: self.pos
            size: self.size
    FloatLayout:
        Button:
            text: "HELP"
            size_hint: (0.3,0.1)
            pos_hint: {"x": 0.01, "y": 0.85}
            background_color: (0.6, 0.85, 0.92, 1)
        Button:
            text: "BACK"
            size_hint: (0.3,0.1)
            pos_hint: {"x": 0.69, "y": 0.85}
            background_color: (0.6, 0.85, 0.92, 1)
            # switches screen when pressed
            on_release: app.root.current = "home"

        BoxLayout:
            orientation: "vertical"
            size_hint: (1,0.85)
            pos_hint : {"x":0,"y":0}

            Label:
                text: "Your positions"
                height: "10dp"
                color: (0,0,0,1)

            ScrollView:

                GridLayout:
                    id:portfolio_table
                    cols: 6
                    height: self.minimum_height


<OrderBook>
    name: "OrderBook"
    # sets background colour
    canvas.before:
        Color:
            rgba: (0.12, 0.65, 0.25, 1)
        Rectangle:
            pos: self.pos
            size: self.size
    FloatLayout:
        Button:
            text: "HELP"
            size_hint: (0.3,0.1)
            pos_hint: {"x": 0.01, "y": 0.85}
            background_color: (0.6, 0.85, 0.92, 1)
        Button:
            text: "BACK"
            size_hint: (0.3,0.1)
            pos_hint: {"x": 0.69, "y": 0.85}
            background_color: (0.6, 0.85, 0.92, 1)
            # switches screen when pressed
            on_release: app.root.current = "home"

        BoxLayout:
            orientation: "horizontal"
            size_hint: (1,0.85)
            pos_hint : {"x":0,"y":0}



            GridLayout:
                size_hint_x: 0.5
                id:buy_order_table
                cols: 6
            GridLayout:
                size_hint_x: 0.5
                id:sell_order_table
                cols: 6







